// Generated by CoffeeScript 1.12.3
(function() {
  var $, API_URL, VIBLO_URL, VibloAPI;

  $ = require('jquery');
  VIBLO_URL = 'http://stg.viblo.asia';
  API_URL = VIBLO_URL+'/api';

  module.exports = VibloAPI = {
    getServerHost: function(){
      return VIBLO_URL;
    },
    getApiKey: function() {
      return atom.config.get('viblo-atom-plugin.apiToken');
    },
    getPublishPostURL: function(source) {
      return API_URL + "/publish/post";
    },
    publish: function(post) {
      var _this = this;
      return new Promise(function(resolve) {
        var url;
        url = _this.getPublishPostURL();
        return $.ajax(url, {
          beforeSend: function(xhr, settings) {
            xhr.setRequestHeader('Authorization', 'Bearer ' + _this.getApiKey());
            xhr.setRequestHeader('Accept', 'application/json');
          },
          data: post,
          method: 'POST',
          success: function(data) {
            return resolve(data);
          },
          error: function(response) {
            if (response.status == 422 && typeof response.responseJSON !== 'undefined') {
              return resolve({
                success: false,
                errors: response.responseJSON
              });
            }
            return resolve({
              success: false,
              statusText: response.statusText
            });
          }
        });
      });
    }
  };

  return VibloAPI;

}).call(this);
